// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Pokemon from "./islands/Pokemon.tsx";
import * as $Quotes from "./islands/Quotes.tsx";
import * as $Users from "./islands/Users.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Pokemon.tsx": $Pokemon,
    "./islands/Quotes.tsx": $Quotes,
    "./islands/Users.tsx": $Users,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
