// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $airport from "./routes/airport.tsx";
import * as $index from "./routes/index.tsx";
import * as $jokes from "./routes/jokes.tsx";
import * as $recipe from "./routes/recipe.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/airport.tsx": $airport,
    "./routes/index.tsx": $index,
    "./routes/jokes.tsx": $jokes,
    "./routes/recipe.tsx": $recipe,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
