// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_message from "./routes/api/message.ts";
import * as $create_contact from "./routes/create/contact.tsx";
import * as $edit_contact_id_ from "./routes/edit/contact/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $message_id_ from "./routes/message/[id].tsx";
import * as $chat from "./islands/chat.tsx";
import * as $contact_create_form from "./islands/contact-create-form.tsx";
import * as $contact_edit_form from "./islands/contact-edit-form.tsx";
import * as $contact_list from "./islands/contact-list.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/message.ts": $api_message,
    "./routes/create/contact.tsx": $create_contact,
    "./routes/edit/contact/[id].tsx": $edit_contact_id_,
    "./routes/index.tsx": $index,
    "./routes/message/[id].tsx": $message_id_,
  },
  islands: {
    "./islands/chat.tsx": $chat,
    "./islands/contact-create-form.tsx": $contact_create_form,
    "./islands/contact-edit-form.tsx": $contact_edit_form,
    "./islands/contact-list.tsx": $contact_list,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
